---
# tasks file for lighthouse-role
# Ставим Git
- name: Install Git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
# Скачиваем с github.com lighthouse
- name: Copy lighthouse from git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_git }}"
    version: master
    dest: "{{ lighthouse_dir }}"
# Создаем конфиг для nginx
- name: Create config
  become: true
  ansible.builtin.template:
    src: lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: Reload nginx service
